### ISSUE TITLE
Provide plugin support

### ISSUE THREAD

**Issue by ereOn** [freelan-developers/plix#3]
Plix need to support external plugins that must be able to:
- Modify the global variables.
- Modify the matrix.
- Modify the exclusion matrix.
- Depend on and load other plugins.
- Modify the `install`, `script`, ... command lists.

If a plugin includes unused dimension in the matrix, those **must not** show up as unused-warnings when running as it would be hard, if not impossible, for the user to fix those.

Plugins must be specified via their Python path and will be processed in order **before** the final configuration is shown to the user. This gives a chance to the user to review the final configuration.

The proposed syntax is:

```
plugins:
  - plix.plugins.PythonPlugin
```

Plugins can also take options, in which case the following form should be used:

```
plugins:
  - name: plix.plugins.PythonPlugin
    options:
      enabled_versions: [2.7, 3.4]
```
